### ISSUE TITLE
Bug in Unlock Function

### ISSUE THREAD

**Issue by lth08091998** [sixteen/peacerelay#16]
- In the current Unlock, we fetch the value of the receiver and the transferred value from rlpReceipt, however rlpReceipt is not used in checkReceiptProof => Malicious users can use whatever rlpReceipt value they want.

![111](https://user-images.githubusercontent.com/21095940/36059892-b9b91822-0e78-11e8-8888-806ccafc414b.png)

**Comment by Anyhowclick** [comment]
1) rlpReceipt and recValue are actually the same thing, so the rlpReceipt input paramter can be removed.
2) blockHashes of trx and receipts are the same (they should be). Hence, we can use just 1 of them.
3) If both proofs (checkReceiptProof and checkTxProof) are valid, then we can assured that the transaction and corresponding receipt is valid.
